import ServiceItemCard from "./service_itemCard";
import service from "../../data/service.json";

function ServiceTabAll() {
  return (
    <ul id="tabNewsContent1" className="list_card list_card_type2">
      <ServiceItemCard
        txt_cate={service.txt_cate[0]}
        tit_card={service.tit_card_kakaotalk[0]}
        img_name={"service_kakaotalk_thumb_1.webp"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[0]}
        tit_card={service.tit_card_kakaotalk[1]}
        img_name={"service_kakaotalk_thumb_2.webp"}
        txt_keyword1={"#보이스룸"}
        txt_keyword2={"#오픈채팅"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[0]}
        tit_card={service.tit_card_kakaotalk[2]}
        img_name={"service_kakaotalk_thumb_3.webp"}
        txt_keyword1={"#일정관리"}
        txt_keyword2={"#친구초대"}
        txt_keyword3={"#카톡알림"}
        txt_keyword4={"#캘린더"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[4]}
        tit_card={service.tit_card_entertainment[0]}
        img_name={"service_entertainment_thumb_1.webp"}
        txt_keyword1={"#엔터테인먼트"}
        txt_keyword2={"#웹툰"}
        txt_keyword3={"#카카오웹툰"}
        txt_keyword4={"#컨텐츠"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[3]}
        tit_card={service.tit_card_commerce[0]}
        img_name={"service_commerce_thumb_1.webp"}
        txt_keyword1={"#개인화추천"}
        txt_keyword2={"#쇼핑"}
        txt_keyword3={"#스타일"}
        txt_keyword4={"#지그재그"}
        txt_keyword5={"#패션"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[6]}
        tit_card={service.tit_card_AI_blockchain[0]}
        img_name={"service_ai_thumb_1.webp"}
        txt_keyword1={"#B2B"}
        txt_keyword2={"#기업솔루션"}
        txt_keyword3={"#카카오i클라우드"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[5]}
        tit_card={service.tit_card_business[0]}
        img_name={"service_business_thumb_1.webp"}
        txt_keyword1={"#AI솔루션"}
        txt_keyword2={"#B2B"}
        txt_keyword3={"#비즈니스"}
        txt_keyword4={"#인공지능"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[2]}
        tit_card={service.tit_card_lifestyle[0]}
        img_name={"service_life_thumb_1.webp"}
        txt_keyword1={"#길안내"}
        txt_keyword2={"#내비게이션"}
        txt_keyword3={"#내차관리"}
        txt_keyword4={"#모빌리티"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[3]}
        tit_card={service.tit_card_commerce[1]}
        img_name={"service_commerce_thumb_2.webp"}
        txt_keyword1={"#b2b선물"}
        txt_keyword2={"#비즈니스선물"}
        txt_keyword3={"#선물하기"}
        txt_keyword4={"#카카오톡"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[5]}
        tit_card={service.tit_card_business[1]}
        img_name={"service_business_thumb_2.webp"}
        txt_keyword1={"#ai"}
        txt_keyword2={"#비즈니스"}
        txt_keyword3={"#언택트"}
        txt_keyword4={"#업무메신저"}
        txt_keyword5={"#카카오워크"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[2]}
        tit_card={service.tit_card_lifestyle[1]}
        img_name={"service_life_thumb_2.webp"}
        txt_keyword1={"#내비게이션"}
        txt_keyword2={"#디스플레이"}
        txt_keyword3={"#모빌리티"}
        txt_keyword4={"#스마트홈"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[5]}
        tit_card={service.tit_card_business[2]}
        img_name={"service_business_thumb_3.webp"}
        txt_keyword1={"#기업문화"}
        txt_keyword2={"#비즈니스"}
        txt_keyword3={"#아지트"}
        txt_keyword4={"#업무플랫폼"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[4]}
        tit_card={service.tit_card_entertainment[1]}
        img_name={"service_entertainment_thumb_2.webp"}
        txt_keyword1={"#기다리면무료"}
        txt_keyword2={"#엔터테인먼트"}
        txt_keyword3={"#웹소설"}
        txt_keyword4={"#웹툰"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[2]}
        tit_card={service.tit_card_lifestyle[2]}
        img_name={"service_life_thumb_3.webp"}
        txt_keyword1={"#같지만다른은행"}
        txt_keyword2={"#은행"}
        txt_keyword3={"#인터넷전문은행"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[0]}
        tit_card={service.tit_card_kakaotalk[3]}
        img_name={"service_kakaotalk_thumb_4.webp"}
        txt_keyword1={"#비즈니스"}
        txt_keyword2={"#채널"}
        txt_keyword3={"#카카오톡채널"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[0]}
        tit_card={service.tit_card_kakaotalk[4]}
        img_name={"service_kakaotalk_thumb_5.webp"}
        txt_keyword1={"#이모티콘"}
        txt_keyword2={"#이모티콘플러스"}
        txt_keyword3={"#카카오이모티콘"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[2]}
        tit_card={service.tit_card_lifestyle[3]}
        img_name={"service_life_thumb_4.webp"}
        txt_keyword1={"#결제"}
        txt_keyword2={"#금융"}
        txt_keyword3={"#송금"}
        txt_keyword4={"#카카오페이"}
        txt_keyword5={"#테크핀"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[2]}
        tit_card={service.tit_card_lifestyle[4]}
        img_name={"service_life_thumb_5.webp"}
        txt_keyword1={"#라이프"}
        txt_keyword2={"#뷰티"}
        txt_keyword3={"#카카오헤어샵"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[4]}
        tit_card={service.tit_card_entertainment[2]}
        img_name={"service_entertainment_thumb_3.webp"}
        txt_keyword1={"#드라마"}
        txt_keyword2={"#라이브"}
        txt_keyword3={"#예능"}
        txt_keyword4={"#오리지널"}
        txt_keyword5={"#카카오TV"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[4]}
        tit_card={service.tit_card_entertainment[3]}
        img_name={"service_entertainment_thumb_4.webp"}
        txt_keyword1={"#만화"}
        txt_keyword2={"#소설"}
        txt_keyword3={"#웹툰"}
        txt_keyword4={"#콘텐츠"}
        txt_keyword5={"#픽코마"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[3]}
        tit_card={service.tit_card_commerce[2]}
        img_name={"service_commerce_thumb_3.webp"}
        txt_keyword1={"#라이브커머스"}
        txt_keyword2={"#카카오쇼핑라이브"}
        txt_keyword3={"#커머스"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[1]}
        tit_card={service.tit_card_communication[0]}
        img_name={"service_communication_thumb_1.webp"}
        txt_keyword1={"#블로그"}
        txt_keyword2={"#수익"}
        txt_keyword3={"#커뮤니케이션"}
        txt_keyword4={"#콘텐츠"}
        txt_keyword5={"#티스토리"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[0]}
        tit_card={service.tit_card_kakaotalk[5]}
        img_name={"service_kakaotalk_thumb_6.webp"}
        txt_keyword1={"#o2o"}
        txt_keyword2={"#배달"}
        txt_keyword3={"#주문"}
        txt_keyword4={"#카카오톡주문하기"}
        txt_keyword5={"#픽업"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[0]}
        tit_card={service.tit_card_kakaotalk[6]}
        img_name={"service_kakaotalk_thumb_7.webp"}
        txt_keyword1={"#카카오메일"}
        txt_keyword2={"#커뮤니케이션"}
        txt_keyword3={"#톡메일"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[1]}
        tit_card={service.tit_card_communication[1]}
        img_name={"service_communication_thumb_2.webp"}
        txt_keyword1={"#검색"}
        txt_keyword2={"#뉴스"}
        txt_keyword3={"#다음앱"}
        txt_keyword4={"#콘텐츠"}
        txt_keyword5={"#포털"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[1]}
        tit_card={service.tit_card_communication[2]}
        img_name={"service_communication_thumb_3.webp"}
        txt_keyword1={"#글쓰기"}
        txt_keyword2={"#브런치"}
        txt_keyword3={"#브런치북"}
        txt_keyword4={"#작가"}
        txt_keyword5={"#창작"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[2]}
        tit_card={service.tit_card_lifestyle[5]}
        img_name={"service_life_thumb_6.webp"}
        txt_keyword1={"#maas"}
        txt_keyword2={"#모빌리티"}
        txt_keyword3={"#이동플랫폼"}
        txt_keyword4={"#카카오T"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[0]}
        tit_card={service.tit_card_kakaotalk[7]}
        img_name={"service_kakaotalk_thumb_8.webp"}
        txt_keyword1={"#간편로그인"}
        txt_keyword2={"#전자증명서"}
        txt_keyword3={"#카카오인증서"}
        txt_keyword4={"#톡명함"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[4]}
        tit_card={service.tit_card_entertainment[4]}
        img_name={"service_entertainment_thumb_5.webp"}
        txt_keyword1={"#k팝"}
        txt_keyword2={"#mma"}
        txt_keyword3={"#멜론"}
        txt_keyword4={"#멜론차트"}
        txt_keyword5={"#뮤직앱"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[4]}
        tit_card={service.tit_card_entertainment[5]}
        img_name={"service_entertainment_thumb_6.webp"}
        txt_keyword1={"#니니즈"}
        txt_keyword2={"#니니툰즈"}
        txt_keyword3={"#죠르디"}
        txt_keyword4={"#죠르디24시"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[2]}
        tit_card={service.tit_card_lifestyle[6]}
        img_name={"service_life_thumb_7.webp"}
        txt_keyword1={"#모빌리티"}
        txt_keyword2={"#지도"}
        txt_keyword3={"#카카오맵"}
        txt_keyword4={"#카카오버스"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[4]}
        tit_card={service.tit_card_entertainment[6]}
        img_name={"service_entertainment_thumb_7.webp"}
        txt_keyword1={"#라이언"}
        txt_keyword2={"#리틀카카오프렌즈"}
        txt_keyword3={"#어피치"}
        txt_keyword4={"#춘식이"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[7]}
        tit_card={service.tit_card_socal_impact[0]}
        img_name={"service_social_thumb_1.webp"}
        txt_keyword1={"#기부"}
        txt_keyword2={"#마음챙김"}
        txt_keyword3={"#사회변화"}
        txt_keyword4={"#소셜임팩트"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[3]}
        tit_card={service.tit_card_commerce[3]}
        img_name={"service_commerce_thumb_4.webp"}
        txt_keyword1={"#쇼핑"}
        txt_keyword2={"#쇼핑하우"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[5]}
        tit_card={service.tit_card_business[3]}
        img_name={"service_business_thumb_4.webp"}
        txt_keyword1={"#비즈도구"}
        txt_keyword2={"#카카오광고"}
        txt_keyword3={"#카카오비즈니스"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[3]}
        tit_card={service.tit_card_commerce[4]}
        img_name={"service_commerce_thumb_5.webp"}
        txt_keyword1={"#공동주문"}
        txt_keyword2={"#주문제작"}
        txt_keyword3={"#카카오메이커스"}
        txt_keyword4={"#커머스"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[3]}
        tit_card={service.tit_card_commerce[5]}
        img_name={"service_commerce_thumb_6.webp"}
        txt_keyword1={"#카카오톡쇼핑하기"}
        txt_keyword2={"#커머스"}
        txt_keyword3={"#톡딜"}
        txt_keyword4={"#톡스토어"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[1]}
        tit_card={service.tit_card_communication[3]}
        img_name={"service_communication_thumb_4.webp"}
        txt_keyword1={"#sns"}
        txt_keyword2={"#사진"}
        txt_keyword3={"#스토리채널"}
        txt_keyword4={"#일상"}
        txt_keyword5={"#카카오스토리"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[1]}
        tit_card={service.tit_card_communication[4]}
        img_name={"service_communication_thumb_5.webp"}
        txt_keyword1={"#공식팬카페"}
        txt_keyword2={"#다음카페"}
        txt_keyword3={"#실시간인기글"}
        txt_keyword4={"#커뮤니티"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[6]}
        tit_card={service.tit_card_AI_blockchain[1]}
        img_name={"service_ai_thumb_2.webp"}
        txt_keyword1={"#그라운드X"}
        txt_keyword2={"#블록체인"}
        txt_keyword3={"#지갑"}
        txt_keyword4={"#클레이튼"}
        txt_keyword5={"#클립"}
      />
      <ServiceItemCard
        txt_cate={service.txt_cate[2]}
        tit_card={service.tit_card_lifestyle[7]}
        img_name={"service_life_thumb_8.webp"}
        txt_keyword1={"#pc온라인게임"}
        txt_keyword2={"#게임광고"}
        txt_keyword3={"#다음게임"}
      />
    </ul>
  );
}

export default ServiceTabAll;
