import ESGItemCard from "./esg_itemCard";
import esg from "../../data/esg.json";

function ESGTabAll() {
  return (
    <ul id="tabNewsContent1" className="list_card list_card_type2">
      <ESGItemCard
        txt_cate={esg.txt_cate[0]}
        tit_card={esg.tit_card_intro[0]}
        img_name={"esg_intro_thumb_1.webp"}
        txt_keyword1={"#ESG 위원회"}
        txt_keyword2={"#이사회"}
        txt_keyword3={"#지속가능경영"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[0]}
        tit_card={esg.tit_card_intro[1]}
        img_name={"esg_intro_thumb_2.webp"}
        txt_keyword1={"#2021년 실적"}
        txt_keyword2={"#사회적책임"}
        txt_keyword3={"#카카오ceo"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[0]}
        tit_card={esg.tit_card_intro[2]}
        img_name={"esg_intro_thumb_3.webp"}
        txt_keyword1={"#2021"}
        txt_keyword2={"#2022"}
        txt_keyword3={"#주요성과"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[0]}
        tit_card={esg.tit_card_intro[3]}
        img_name={"esg_intro_thumb_4.webp"}
        txt_keyword1={"#디지털책임"}
        txt_keyword2={"#사회문제해결"}
        txt_keyword3={"#파트너성장"}
        txt_keyword4={"#환경"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[0]}
        tit_card={esg.tit_card_intro[4]}
        img_name={"esg_intro_thumb_5.webp"}
        txt_keyword1={"#ai"}
        txt_keyword2={"#블록체인"}
        txt_keyword3={"#이동기술"}
        txt_keyword4={"#클라우드"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[0]}
        tit_card={esg.tit_card_intro[5]}
        img_name={"esg_intro_thumb_6.webp"}
        txt_keyword1={"#디지털생태계"}
        txt_keyword2={"#상생기금"}
        txt_keyword3={"#포용성"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[0]}
        tit_card={esg.tit_card_intro[6]}
        img_name={"esg_intro_thumb_7.webp"}
        txt_keyword1={"#DJSI"}
        txt_keyword2={"#KCGS"}
        txt_keyword3={"#MSCI"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[1]}
        tit_card={esg.tit_card_environment[0]}
        img_name={"esg_env_thumb_1.webp"}
        txt_keyword1={"#지속가능경영"}
        txt_keyword2={"#친환경"}
        txt_keyword3={"#환경경영시스템인증"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[1]}
        tit_card={esg.tit_card_environment[1]}
        img_name={"esg_env_thumb_2.webp"}
        txt_keyword1={"#기후변화"}
        txt_keyword2={"#넷제로"}
        txt_keyword3={"#액티브그린이니셔티브"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[1]}
        tit_card={esg.tit_card_environment[2]}
        img_name={"esg_env_thumb_3.webp"}
        txt_keyword1={"#데이터센터"}
        txt_keyword2={"#에너지효율"}
        txt_keyword3={"#친환경"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[1]}
        tit_card={esg.tit_card_environment[3]}
        img_name={"esg_env_thumb_4.webp"}
        txt_keyword1={"#그린디지털"}
        txt_keyword2={"#서비스"}
        txt_keyword3={"#환경캠페인"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[2]}
        tit_card={esg.tit_card_social[0]}
        img_name={"esg_social_thumb_1.webp"}
        txt_keyword1={"#다양성"}
        txt_keyword2={"#성장지원"}
        txt_keyword3={"#인권경영"}
        txt_keyword4={"#임직원"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[2]}
        tit_card={esg.tit_card_social[1]}
        img_name={"esg_social_thumb_2.webp"}
        txt_keyword1={"#디지털책임"}
        txt_keyword2={"#지속가능한환경"}
        txt_keyword3={"#파트너성장"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[2]}
        tit_card={esg.tit_card_social[2]}
        img_name={"esg_social_thumb_3.webp"}
        txt_keyword1={"#개인정보보호"}
        txt_keyword2={"#기업의디지털책임"}
        txt_keyword3={"#정보보안"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[2]}
        tit_card={esg.tit_card_social[3]}
        img_name={"esg_social_thumb_4.webp"}
        txt_keyword1={"#사회문제해결"}
        txt_keyword2={"#소셜임팩트"}
        txt_keyword3={"#커뮤니티"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[3]}
        tit_card={esg.tit_card_governance[0]}
        img_name={"esg_governance_thumb_1.webp"}
        txt_keyword1={"#ESG 위원회"}
        txt_keyword2={"#이사회"}
        txt_keyword3={"#지배구조"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[3]}
        tit_card={esg.tit_card_governance[1]}
        img_name={"esg_governance_thumb_2.webp"}
        txt_keyword1={"#리스크관리체계"}
        txt_keyword2={"#잠재리스크"}
        txt_keyword3={"#통합리스크"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[3]}
        tit_card={esg.tit_card_governance[2]}
        img_name={"esg_governance_thumb_3.webp"}
        txt_keyword1={"#사이버윤리센터"}
        txt_keyword2={"#상임윤리위원회"}
        txt_keyword3={"#윤리교육"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[4]}
        tit_card={esg.tit_card_report[0]}
        img_name={"esg_report_thumb_1.webp"}
        txt_keyword1={"#이해관계소통"}
        txt_keyword2={"#지속가능경영"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[4]}
        tit_card={esg.tit_card_report[1]}
        img_name={"esg_report_thumb_2.webp"}
        txt_keyword1={"#감사기구"}
        txt_keyword2={"#기업지배구조정책"}
        txt_keyword3={"#이사회"}
        txt_keyword4={"#주주"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[4]}
        tit_card={esg.tit_card_report[2]}
        img_name={"esg_report_thumb_3.webp"}
        txt_keyword1={"#Partners with Kakao"}
        txt_keyword2={"#상생"}
      />
      <ESGItemCard
        txt_cate={esg.txt_cate[4]}
        tit_card={esg.tit_card_report[3]}
        img_name={"esg_report_thumb_4.webp"}
        txt_keyword1={"#ESG보고서"}
        txt_keyword2={"#규정&정책"}
        txt_keyword3={"#기업지배구조보고서"}
      />
    </ul>
  );
}

export default ESGTabAll;
