import TechItemCard from "./tech_itemCard";
import tech from "../../data/tech.json";

function TechTabAll() {
  return (
    <ul id="tabNewsContent1" className="list_card list_card_type2">
      <TechItemCard
        txt_cate={tech.txt_cate[5]}
        tit_card={tech.tit_card_ifkakao[0]}
        img_name={"tech_ifkakao_thumb_1.webp"}
        txt_keyword1={"#기술로만드는더나은세상"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[5]}
        tit_card={tech.tit_card_ifkakao[1]}
        img_name={"tech_ifkakao_thumb_2.webp"}
        txt_keyword1={"#함께나아가는더나은세상"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[5]}
        tit_card={tech.tit_card_ifkakao[2]}
        img_name={"tech_ifkakao_thumb_3.webp"}
        txt_keyword1={"#연결을넘어"}
        txt_keyword2={"#의미있는관계로"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[5]}
        tit_card={tech.tit_card_ifkakao[3]}
        img_name={"tech_ifkakao_thumb_4.webp"}
        txt_keyword1={"#관심많은"}
        txt_keyword2={"#세상만사"}
        txt_keyword3={"#카카오개발자"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[5]}
        tit_card={tech.tit_card_ifkakao[4]}
        img_name={"tech_ifkakao_thumb_5.webp"}
        txt_keyword1={"#ai"}
        txt_keyword2={"#세상은전부개발거리"}
        txt_keyword3={"#인공지능"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[2]}
        tit_card={tech.tit_card_tech_service[0]}
        img_name={"tech_service_thumb_1.webp"}
        txt_keyword1={"#ai"}
        txt_keyword2={"#comprehension"}
        txt_keyword3={"#ocr"}
        txt_keyword4={"#search"}
        txt_keyword5={"#tech"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[2]}
        tit_card={tech.tit_card_tech_service[1]}
        img_name={"tech_service_thumb_2.webp"}
        txt_keyword1={"#compliance"}
        txt_keyword2={"#kakaoolive"}
        txt_keyword3={"#license"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[3]}
        tit_card={tech.tit_card_tech_contents[0]}
        img_name={"tech_contents_thumb_1.webp"}
        txt_keyword1={"#ai"}
        txt_keyword2={"#kakaokrew"}
        txt_keyword3={"#tech"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[0]}
        tit_card={tech.tit_card_kakao_tech[0]}
        img_name={"tech_kakao_tech_thumb_1.webp"}
        txt_keyword1={"#blog"}
        txt_keyword2={"#engineering"}
        txt_keyword3={"#service"}
        txt_keyword4={"#software"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[1]}
        tit_card={tech.tit_card_tech_platform[0]}
        img_name={"tech_platform_thumb_1.webp"}
        txt_keyword1={"#ai"}
        txt_keyword2={"#engineering"}
        txt_keyword3={"#sdk"}
        txt_keyword4={"#software"}
        txt_keyword5={"#tech"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[4]}
        tit_card={tech.tit_card_tech_event[0]}
        img_name={"tech_event_thumb_1.webp"}
        txt_keyword1={"#ai"}
        txt_keyword2={"#al"}
        txt_keyword3={"#competition"}
        txt_keyword4={"#ml"}
        txt_keyword5={"#tech"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[1]}
        tit_card={tech.tit_card_tech_platform[1]}
        img_name={"tech_platform_thumb_2.webp"}
        txt_keyword1={"#ai"}
        txt_keyword2={"#tech"}
        txt_keyword3={"#techplatform"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[2]}
        tit_card={tech.tit_card_tech_service[2]}
        img_name={"tech_service_thumb_3.webp"}
        txt_keyword1={"#engineering"}
        txt_keyword2={"#opensource"}
        txt_keyword3={"#software"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[2]}
        tit_card={tech.tit_card_tech_service[3]}
        img_name={"tech_service_thumb_4.webp"}
        txt_keyword1={"#engineering"}
        txt_keyword2={"#opensource"}
        txt_keyword3={"#software"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[3]}
        tit_card={tech.tit_card_tech_contents[1]}
        img_name={"tech_contents_thumb_2.webp"}
        txt_keyword1={"#ai"}
        txt_keyword2={"#brain"}
        txt_keyword3={"#cloud"}
        txt_keyword4={"#paper"}
        txt_keyword5={"#tech"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[1]}
        tit_card={tech.tit_card_tech_platform[2]}
        img_name={"tech_platform_thumb_3.webp"}
        txt_keyword1={"#blockchain"}
        txt_keyword2={"#groundx"}
        txt_keyword3={"#tech"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[3]}
        tit_card={tech.tit_card_tech_contents[2]}
        img_name={"tech_contents_thumb_3.webp"}
        txt_keyword1={"#mobility"}
        txt_keyword2={"#reoirt"}
        txt_keyword3={"#story"}
        txt_keyword4={"#tech"}
      />
      <TechItemCard
        txt_cate={tech.txt_cate[2]}
        tit_card={tech.tit_card_tech_service[4]}
        img_name={"tech_service_thumb_5.webp"}
        txt_keyword1={"#ai"}
        txt_keyword2={"#dl"}
        txt_keyword3={"#ml"}
        txt_keyword4={"#system"}
        txt_keyword5={"#tech"}
      />
    </ul>
  );
}

export default TechTabAll;
